### Handwritten Digit Recognition using Support Vector Machines
Done by \
    Christo Sojan \
    2020BCS0069



In [1]:
# Support Vector Machine (SVM)
# Importing the libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
# Mounting Google Drive
from google.colab import drive
drive.mount("/content/gdrive")

# Using dataset from Google Drive
train_dataset = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/ML Project/mnist_train.csv')
test_dataset = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/ML Project/mnist_test.csv')

Mounted at /content/gdrive


In [3]:
## Separating the X and Y variable
y = train_dataset['label'].values.astype('int32')
## Dropping the variable 'label' from X variable
X = train_dataset.drop(columns = 'label').values.astype('float32')

## Normalization
X = X/255.0

# Scaling the features
X_scaled = scale(X)

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, train_size = 0.8, random_state = 10)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_data.py:240: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_data.py:259: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn(


In [4]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
# Training the SVM model on the Training set
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [6]:
# Predicting a new result
print(classifier.predict(sc.transform(X_test)))

[3 5 0 ... 2 4 9]


In [7]:
# Prediction
y_train_svc = classifier.predict(X_train)
y_pred_svc = classifier.predict(X_test)

In [8]:
# Making the Confusion Matrix
cm = confusion_matrix(y_test, y_pred_svc)
print('Confusion Matrix :\n\n', cm)

Confusion Matrix :

 [[1083    0    9    3    3   11   10    1    5    2]
 [   0 1324    5    4    0    1    0    2    8    1]
 [  10   19 1128   20   14    8   15   13   12    2]
 [   4    7   35 1070    1   36    3    1   17    8]
 [   2    4   18    0 1122    4    6    8    3   33]
 [  13    5   12   42   12  980    9    2   24    5]
 [  16    5   25    0    8   18 1127    0    2    0]
 [   5    5   11   13   25    5    1 1219    4   48]
 [  10   25   38   38    6   28   11    7  987    4]
 [   3    1    8   13   49    9    0   30   18  979]]


In [9]:
svc_train = accuracy_score(y_train,y_train_svc)
svc_accuracy = accuracy_score(y_test, y_pred_svc)

print("Train Accuracy score: {}".format(svc_train))
print("Test Accuracy score : {}".format(svc_accuracy))
print(classification_report(y_test, y_pred_svc))

Train Accuracy score: 0.9864583333333333
Test Accuracy score : 0.91825
              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1127
           1       0.95      0.98      0.97      1345
           2       0.88      0.91      0.89      1241
           3       0.89      0.91      0.90      1182
           4       0.90      0.94      0.92      1200
           5       0.89      0.89      0.89      1104
           6       0.95      0.94      0.95      1201
           7       0.95      0.91      0.93      1336
           8       0.91      0.86      0.88      1154
           9       0.90      0.88      0.89      1110

    accuracy                           0.92     12000
   macro avg       0.92      0.92      0.92     12000
weighted avg       0.92      0.92      0.92     12000

